# Generated by Django 2.2.10 on 2020-03-15 13:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=18)),
                ('room', models.CharField(max_length=8)),
                ('dob', models.DateField(default=datetime.datetime(2020, 3, 15, 20, 52, 13, 304681))),
                ('active', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='c:\\JS\\final\\staticfiles\\avatar.png', upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
